### ISSUE TITLE
Feature between Every and Interval jobs in rufus-scheduler

### ISSUE THREAD

**Issue by gihnius** [moove-it/sidekiq-scheduler#103]
https://github.com/jmettraux/rufus-scheduler#everyjob-methods

> Every jobs use a time duration between each start of their execution, while interval jobs use a time duration between the end of an execution and the start of the next.

any equivalent feature in sidekiq-scheduler ?

**Comment by snmgian** [comment]
Hi,

_every_ and _interval_ jobs should work out of the box. Here's a sample configuration:

```yml
  EveryCheckWorker:
    every: "1m"
    class: EveryCheckWorker
    queue: low
    description: "every 1 minute"
```

Let me know if you face any problems.
