### ISSUE TITLE
Receiving scheduled date / metadata as an argument?

### ISSUE THREAD

**Issue by ervoiox** [moove-it/sidekiq-scheduler#163]
Hi,

Is it possible to have our scheduled jobs receive an argument of metadata, such as the date of when the job was scheduled?

For example if I have a job that runs on the 6th of the month, I want to receive a timestamp as an argument to `perform`. We have jobs that rely on dates, so calling `DateTime.current` inside the scheduled job `perform` is not reliable as the job could be executed at a different date from when it was scheduled (ie: failure then retrying or being a duplicate being run at another date, or sitting in the queue). If the `schedule.yml` config can support a flag or something to pass in the date of the scheduled execution, this helps our jobs be more idempotent.

For example if we could do something like:

```yml
# scheduler.yml
monthly_scheduler:
  class: MonthlyScheduler
  cron: '0 2 6 * *'
  description: 'Monthly scheduler job that creates jobs, runs on the 6th of the month at 2am.'
  queue: 'scheduled'
  metadata: true
```

```ruby
# worker
class MonthlyScheduler
  include Sidekiq::worker

  sidekiq_options queue: 'scheduled'

  def perform(metadata)
    date = metadata['scheduled_date'] # => '2017-01-01T02:00:00+00:00'

    Tasks.some_scope.each do |id|
       AnotherJob.perform_async(date, id)
      end
   end
end
```

```ruby
# metadata structure
# simple hash

{
   # string of the timestamp of the date the job was scheduled to run
   # example strftime format (%Y-%m-%d %H:%M:%S.%N)
   # should be a format that can be passed to Time.parse by default, probably iso8601? (%FT%T%z)
   "scheduled_date" => "2017-01-01T02:00:00+00:00"
}
```

What do you think?
