### ISSUE TITLE
WARN: NameError: uninitialized constant Test::Listing

### ISSUE THREAD

**Issue by tirdadc** [moove-it/sidekiq-scheduler#174]
in my `perform` method, I'm calling some class methods on my `Listing` model. It results in an error. What do I need to include to have access to the Rails models within the scope of the `perform` method of my scheduler class?

**Comment by snmgian** [comment]
Hey @tirdadc 

It really depends on how you have had setup your app. Are you using ActiveJob?

If you are using ActiveJob and Rails, you'll need smth like:

``` ruby
# app/workers/hello_world_worker.rb
class HelloWorldWorker < ApplicationJob
  self.queue_adapter = :sidekiq

  def perform
    p Article.all
  end
end
```

If you are using Sidekiq workers and Rails:

``` ruby
# app/workers/hello_world_worker.rb
class HelloWorldWorker
  include Sidekiq::Worker

  def perform
    p Article.all
  end
end
```

Config file (for both ActiveJob and Sidekiq workers):
``` yaml
# config/sidekiq.yml

:schedule:
  hello_world:
    every: 20s
    class: HelloWorldWorker
```

Run it with `bundle exec sidekiq`

**Comment by tirdadc** [comment]
I ended up just using a regular ActiveJob class and referencing that, without the `test-scheduler.rb` stuff passed with `-r` to sidekiq and it's working great.

Maybe I can submit a small PR for the README so that using this with ActiveJob is more clearly explained, with the following example?

```ruby
# jobs/hello_world_job.rb

class HelloWorldJob < ApplicationJob
  queue as :default

  def perform
    p Article.all
  end
end
```

```yaml
#config/sidekiq.yml

:schedule:
  hello_world:
    every: 1m   # Runs once per minute
    class: HelloWorldJob
```
