### ISSUE TITLE
Launching from ruby script

### ISSUE THREAD

**Issue by TheRusskiy** [moove-it/sidekiq-scheduler#180]
First of all, thank you for the gem!

I have a question, I don't want to run scheduler as a part of neither web server, nor sidekiq.
To avoid multiple jobs being scheduled I want to run this on a separate server via a separate script.
Is it possible to do this?

**Comment by snmgian** [comment]
sidekiq provides a Redis connection, and process graceful termination. So, right now is not possible to run sidekiq-scheduler without running sidekiq.

Said that, there are two options:

1. Configure all of your servers, except one, with the `enabled` flag being `false`. See https://github.com/moove-it/sidekiq-scheduler/#configuration-options. In this way, sidekiq-scheduler will run in only one of your servers.

2. The same as option 1, but also configure an inexistent queue on the only server that has sidekiq-scheduler enabled. In this way, your sidekiq-scheduler server will not perform any sidekiq job.

```yaml
# sidekiq.yml
:queues:
  - sidekiq-scheduler # a queue to which no job is pushed

:concurrency: 1   # just to avoid too many unnecessary queries to Redis

:enabled: true  # it's true by default, so you can skip this

:schedule:
  hello_world:
    cron: 0 * * * * *
    class: HelloWorld
```

If you have any additional question, please ask.
