### ISSUE TITLE
Schedule not respecting environments

### ISSUE THREAD

**Issue by cweilemann** [moove-it/sidekiq-scheduler#212]
Our production schedule runs quite often via cron (once every 15 seconds in some cases). This causes a lot of debug log pollution in our development.log, even routing the Sidekiq logs to `log/sidekiq.log`.

I tried setting up my config/sidekiq.yml to something like:

```
:timeout: 30
:concurrency: 25

:queues:
  - critical
  - high
  - default
  - low

production:
  :schedule:
    <schedule list per examples>

development:
  #:verbose: true
  :logfile: ./log/sidekiq.log

  :schedule:
     <less verbose schedule, same as above>
```

Yet, Sidekiq scheduler seems to be loading the production schedule regardless.

Does sidekiq-scheduler not support the above? Is there a best practice for this?

**Comment by snmgian** [comment]
Hi @cweilemann 

Could you give me a sample of the logs you are seeing that shouldn't be? Thanks.

**Comment by cweilemann** [comment]
Not really, because I don't think they'd be very helpful. Basically it's running jobs as listed under the production schedule, not development. I'm mostly wondering if this gem supports what I'm trying to do above, or if there's a better way to make different schedules in different environments work.

**Comment by snmgian** [comment]
I actually tested with different schedules for each environment and worked as expected, so I thought the issue was regarding logging verbosity ...

Could you verify that environment is being set correctly? Which commands do you use to run sidekiq? `-e` modifier is for setting the env

**Comment by cweilemann** [comment]
The exact command we're running (within a docker container) is:

```
bundle exec sidekiq -e $RAILS_ENV -C config/sidekiq.yml
```

`RAILS_ENV` is set in all environments, and defaults to `development` locally.

**Comment by snmgian** [comment]
I tried to reproduce your issue, so I setup a test project here: https://github.com/snmgian/212-environments-sidekiq-scheduler

`sidekiq` config:
```yaml

:concurrency: 1

production:
  :verbose: false
  :logfile: ./log/sidekiq-production.log
  :schedule:
    SampleJob:
      args: ['production']
      every: '20s'

development:
  :verbose: true
  :logfile: ./log/sidekiq-development.log
  :schedule:
    SampleJob:
      args: ['development']
      every: '7s'
```

Running the following commands: 
 - `bundle exec sidekiq -e production`
 - `bundle exec sidekiq`

Will take either one schedule or the other depending on the environment.

Please tell me if there's something different and of significance between this test project and your project.
