### ISSUE TITLE
Need support for dynamically loading yaml config file

### ISSUE THREAD

**Issue by ACEMerlin** [moove-it/sidekiq-scheduler#222]
I have around 100 jobs written in `sidetiq` and I want to refactor them all to use `sidekiq-scheduler`. The thing is that many of them are using custom logic to determine whether to run or not. So this is what I attempt:

```yaml
# sidekiq_scheduler.yml
some_fancy_job:
  cron: '0 * * * * *'
  class: SomeFancyJob
  enabled: <%= some_logic_which_returns_true_or_false %>
...
```
```ruby
...
config.on(:startup) do
    schedule_file = "config/sidekiq_scheduler.yml"
    result = ERB.new(File.read(Rails.root.join(schedule_file))).result
    Sidekiq.schedule = YAML.load(result)
    Sidekiq::Scheduler.reload_schedule!
end
...
```

It works, but I don't know how to reload. It just loads the file once on start. The `dynamic` option doesn't seem to help.

Or is there a better way to do this?
