### ISSUE TITLE
set_schedule function 

### ISSUE THREAD

**Issue by magedmakled** [moove-it/sidekiq-scheduler#235]
My understanding is that the function `set_schedule` sets previously scheduled delivery. Is there a way to `Add` to the schedule without overwriting it using all the helper tools like `every, at, in`?

**Comment by snmgian** [comment]
set_schedule receives a name `(String)`, and a job schedule `(Hash)`. If a job schedule already exists with the given name, it will update it, otherwise it will add the schedule.

So, for example, if in `config/sidekiq.yml` you have:

```yaml
:schedule:
  hello_world:
    cron: '0 * * * * *'   # Runs once per minute
    class: HelloWorld
```

and then you do: 
```ruby
Sidekiq.set_schedule('hello_world', { cron: '0 0 * * * *', 'class' => 'HelloWorld' })
```

`HelloWorld` will be pushed into sidekiq once per hour at `min = 0, sec = 0`)
