### ISSUE TITLE
Best way to schedule per environment?

### ISSUE THREAD

**Issue by sterankin** [moove-it/sidekiq-scheduler#256]
In some environments I may want to run a job more often, in other environments I may not want to run a job at all.

What is the best way to have different job schedules per Rails environment?  Considering that most non-prod environments would have the same schedule so I would prefer not to have multiple versions of the same schedule everywhere.

I am using the sidekiq yml to schedule the jobs.

Are the jobs scheduled on the client side and not the server or both, and is there a way to restrict it to the client?

Thanks

**Comment by snmgian** [comment]
Hi @sterankin 

You can have smth like this in your `sidekiq.yml` config file:

```yaml
production:
  :verbose: false
  :logfile: ./log/sidekiq-production.log
  :schedule:
    SampleJob:
      args: ['production']
      every: '20s'

development:
  :verbose: true
  :logfile: ./log/sidekiq-development.log
  :schedule:
    SampleJob:
      args: ['development']
      every: '7s'
```
