### ISSUE TITLE
Using with ActiveJob in Rails

### ISSUE THREAD

**Issue by bovender** [moove-it/sidekiq-scheduler#302]
I am having trouble wrapping my head around how to use this in a Rails app. My apologies if this seems dumb.

I have a `HousekeepingJob` that descends from `ActiveJob`. When I reference this in `sidekiq.yml` like this:

```yaml
---
:concurrency: 5
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
:schedule:
  housekeeping:
    class: HousekeepingJob
    every: 1d
    description: Perform daily housekeeping.
```

... then the job is not performed.

When I add `include Sidekiq::Worker` to my `HousekeepingJob` class, I get this error:

```plain
Sidekiq::Worker cannot be included in an ActiveJob: HousekeepingJob (ArgumentError)
```

I'm sure the solution is simple, but what is it?
