### ISSUE TITLE
UI show the queue name 'default'  when set a queue_as in active job

### ISSUE THREAD

**Issue by huobazi** [moove-it/sidekiq-scheduler#303]
When set the queue_as in a active_job, do not set the queue name in sidekiq.yml
the UI show the queue name 'default' 

Gems:
```
    rails (6.0.2.2)
    sidekiq (5.2.8)
    sidekiq-scheduler (3.0.1)
```
application.rb:
```ruby
    config.active_job.queue_adapter = :sidekiq
    config.active_job.queue_name_prefix = "myapp.#{Rails.env}"
    config.active_job.queue_name_delimiter = "."
```
sidekiq initializers:
```ruby
# set the queue_name_prefix and queue_name_delimiter
Sidekiq.configure_server do |config|
  queue_name_prefix = ::ActiveJob::Base.queue_name_prefix
  queue_name_delimiter = ::ActiveJob::Base.queue_name_delimiter
  config.options[:queues] = config.options[:queues].map do |queue_name|
    [queue_name_prefix, queue_name].compact.join(queue_name_delimiter)
  end
end
```

sidekiq.yml:
```yaml
:queues:
  - [overdue_data_cleanup, 5]
:schedule:
  doorkeeper_cleanup:
    cron: "<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * *"
    class: Scheduler::DoorkeeperCleanupJob
    description: "This job queues the expire doorkeeper token to clear"
```
active_job:
```ruby
module Scheduler
  class DoorkeeperCleanupJob < ApplicationJob
    queue_as :overdue_data_cleanup # set queue name
    def perform
    end
  end
end
```
![image](https://user-images.githubusercontent.com/341526/80923144-40dbd580-8db4-11ea-8e9d-70c0584e947e.png)

I think UI should show queue such like 'myapp.development.overdue_data_cleanup' but not 'default'

ref : https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq-scheduler/job_presenter.rb#L48
