### ISSUE TITLE
Not running every day at 2pm as mentioned in the schedule

### ISSUE THREAD

**Issue by altjx** [moove-it/sidekiq-scheduler#304]
Right now I have a few sidekiq schedules set up for every minute, and they run just perfectly fine. However, when trying to set one up that runs every day at 2pm eastern time, no luck.

Here's what my `sidekiq.yml` file looks like:

```
development:  
  :concurrency: 200
  :schedule:
    purge_worker:
      cron: '00 14 * * * * America/Detroit'   # Runs once per minute
      class: PurgeWorker
      queue: development
```

Is this not in the right format?

**Comment by altjx** [comment]
One too many dots. Got it working this way:

```
development:  
  :concurrency: 200
  :schedule:
    purge_worker:
      cron: '16 14 * * * America/Detroit'   # Every day at 2pm eastern
      class: PureWorker
      queue: development
```
