### ISSUE TITLE
Job at Last Day of the Month

### ISSUE THREAD

**Issue by marfoldi-kaligo** [moove-it/sidekiq-scheduler#314]
Hello,
I was trying to schedule a job to 12PM on the last day of each month like this:
```
my_awesome_job:
  enabled: true
  cron: "00 12 L * * Asia/Dubai" # Last day of each month at 12:00pm UAE time
  class: AwesomeWorker
```
Unfortunately seems like it is not making to the `Recurring Jobs`:
![image](https://user-images.githubusercontent.com/60606794/96118848-66851300-0eec-11eb-84db-ae77f7d68de3.png)
Am suspecting that something goes wrong in [SidekiqScheduler:: Scheduler#load_schedule_job](https://github.com/moove-it/sidekiq-scheduler/blob/master/lib/sidekiq-scheduler/scheduler.rb#L115-L125).
I think [rufus-scheduler supports](https://github.com/jmettraux/rufus-scheduler#l-last-day-of-month) the format above.
Would really appreciate some feedback/help on this one.
Thank you. 🙇
