### ISSUE TITLE
Scheduler defined as cron: not executed immediately when fired in UI

### ISSUE THREAD

**Issue by exocode** [moove-it/sidekiq-scheduler#379]
I hope the title describes it, is this behaviour intentional? 

Cron with `every: 1 minute` is fired immediately and crons on sundays are not? 

Maybe I understand it incorrectly: manually clicking crons in UI are there to force fire them immediately?

https://user-images.githubusercontent.com/1597621/167494571-c33c9611-2b6c-4a10-bfb3-f596d8b02737.mov

this is my schedule:

```yaml
:schedule:
  valid_account_scheduler:
    description: "Checks Daily at 00:00h for paid accounts. Deactivates products if not paid."
    #    cron: "@daily"
    every: "1 minute" # each 1 minute
    class: "ValidAccountScheduler"
    queue: default

  weekly_deal_scheduler:
    description: "Calculates (22:00 on Sunday) 'Weekly deals' for each product."
    cron: "0 22 * * 7" # Sunday at 22:00
    class: "WeeklyDealScheduler"
    queue: important
    args:
      - hard: "stuff"
```

and that are my schedule jobs:

```ruby
require 'sidekiq-scheduler'

class WeeklyDealScheduler
  include Sidekiq::Worker

  def perform
    Rails.logger.info "LOGGER info: WeeklyDealScheduler on Sidekiq-server-PID-#{::Process.pid} running..."
  end
end


require 'sidekiq-scheduler'

class ValidAccountScheduler
  include Sidekiq::Worker

  def perform
    Rails.logger.info "LOGGER info: ValidAccountScheduler-#{::Process.pid}"
  end
end

```
