### ISSUE TITLE
Not seeing scheduled tasks in web

### ISSUE THREAD

**Issue by cbetta** [moove-it/sidekiq-scheduler#56]
Hey, just tried the new gem release. This is my sidekiq.yml:

```yml
---
:timeout: 8
:queues:
  - priority_emails
  - emails
  - releases
  - default

:schedule:
  process_emails_due:
    cron: "* * * * *"
    queue: emails
    class: "EmailsDueWorker"

  process_releases_due:
    cron: "* * * * *"
    queue: releases
    class: "ReleasesDueWorker"

  process_releases_expire_on_start:
    cron: "* * * * *"
    queue: releases
    class: "ReleasesExpireOnStartWorker"
```

The tasks are scheduled but somehow I'm not seeing them in the dashboard
