### ISSUE TITLE
Jobs not displayed in web ui

### ISSUE THREAD

**Issue by Crashtown** [moove-it/sidekiq-scheduler#74]
my schedule in config/sidekiq.yml

```yaml
:schedule:
  authenticom_daily_files_import:
    every: 4h
    class: AuthenticomDailyFilesImportWorker
    queue: default
    description: "This job pull data from FTP server and import it to database"

  check_alerts:
    cron: 0 2 * * *
    class: CheckAlertsWorker
    queue: default
    description: "Should check alerts"
```

**Comment by elpic** [comment]
Could you add more information please. 

For example Gemfile.lock

And how do you load the sidekiq (using be sidekiq or from rails) 

Thanks

**Comment by Crashtown** [comment]
Sorry, I tried to reproduce this bug again and everything works now, so I dont remember precisely what it was. 
This is my current working configuration"
I setup schedule in sidekiq.rb initializer at bottom of file:
```ruby
Sidekiq.schedule = YAML.load_file("config/schedule.yml")
```
config/schedule.yml

```yaml
authenticom_daily_files_import:
  cron: "0 4 * * *"
  class: AuthenticomDailyFilesImportWorker
  queue: default
check_alerts:
  cron: "0 2 * * *"
  class: CheckAlertsWorker
  queue: default
```
I'll close this issue and start feature request to adding button for manually enqueueing jobs through web ui
