### ISSUE TITLE
Job is scheduled on each queue.

### ISSUE THREAD

**Issue by maxrosecollins** [moove-it/sidekiq-scheduler#91]
When I schedule a job it is processed on each queue I have.

For example the job will be scheduled and run three times with the following code. Even though it should only run on the `worker` queue it runs on a `worker` queue on both the `reports` and `payment` sidekiqs

Scheduler:
```
:schedule:
  DailyCheckWorker:
    cron: "0 20 00 * * *"
    class: DailyCheckWorker
    queue: worker
    description: "abcdef"
```

Procfile:
```
web: bundle exec puma -C config/puma.rb
reports: bundle exec sidekiq -q reports
worker: bundle exec sidekiq -q worker
payment: bundle exec sidekiq -q payment
```
